name: release goproxy

on:
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out elazarl/goproxy"
        uses: actions/checkout@v3
        with: 
          repository: elazarl/goproxy
          fetch-depth: 0

      - name: "Set up Go"
        uses: actions/setup-go@v4
        with: 
          go-version: '1.20.3'
          
      - name: build
        env:
          CGO_ENABLED: 0
        run: |
          GOOS='linux' GOARCH='amd64' go build -o goproxy examples/goproxy-basic/main.go
          GOOS='windows' GOARCH='amd64' go build -o goproxy.exe examples/goproxy-basic/main.go
          GOOS='darwin' GOARCH='amd64' go build -o goproxy-macos examples/goproxy-basic/main.go
          
      - name: Set tag name
        run: |
          echo "tag_name=v$(date --utc +%Y-%m-%d-%H%M)" >> $GITHUB_ENV
      
      - name: "Create release on GitHub"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          files: |
            goproxy
            goproxy.exe
            goproxy-macos
          
